# Generated by Django 4.2.9 on 2024-04-23 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0008_alter_video_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
