# Generated by Django 4.2.9 on 2024-04-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_genre_video_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
