# Generated by Django 4.2.9 on 2024-04-29 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0012_video_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='format',
            field=models.CharField(choices=[('DVD', 'DVD'), ('Blu-Ray', 'Blu-Ray'), ('UHD', 'UHD'), ('Dual Format: Blu-Ray and DVD', 'Dual Format: Blu-Ray and DVD'), ('Dual Format: UHD and Blu-Ray', 'Dual Format: UHD and Blu-Ray')], default='DVD', max_length=250),
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='videos.video')),
            ],
        ),
    ]
