# Generated by Django 4.2.9 on 2024-04-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_alter_video_format_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
