# Generated by Django 4.2.9 on 2024-05-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_userreview_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='sku',
            field=models.CharField(max_length=254, null=True, unique=True),
        ),
    ]
