# Generated by Django 4.2.9 on 2024-05-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_alter_video_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
