# Generated by Django 4.2.9 on 2024-05-13 13:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_alter_video_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='video_cover'),
        ),
    ]
