# Generated by Django 4.2.9 on 2024-06-04 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0022_alter_region_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='rating',
        ),
    ]
