# Generated by Django 4.2.9 on 2024-05-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customermessage_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessagethread',
            name='order_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
