# Generated by Django 4.2.9 on 2024-05-21 14:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customermessagethread_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessagethread',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customermessage',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='customer.customermessagethread'),
        ),
    ]
