# Generated by Django 4.2.9 on 2024-05-21 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customermessagethread_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessagethread',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customermessagethread',
            name='user_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
