# Generated by Django 4.2.9 on 2024-05-12 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='order_number',
            field=models.UUIDField(default=uuid.UUID('fec9a589-63f3-4af1-a3b6-29e8a63d6b73'), editable=False),
        ),
    ]
