# Generated by Django 4.2.9 on 2024-05-08 20:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_customer_videoorderbasket_order_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.UUID('8a3ddc2a-6576-4e88-ba5b-19cbbda16f0e'), editable=False),
        ),
    ]
