# Generated by Django 4.2.9 on 2024-05-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_customerorder_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='order_number',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
