# Generated by Django 4.2.9 on 2024-05-13 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('checkout', '0004_alter_customerorder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customer.customer'),
        ),
    ]
