# Generated by Django 4.2.9 on 2024-05-08 23:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_original_basket_order_stripe_pid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoorderitem',
            old_name='quantitiy',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.UUID('1fa581cb-13a1-4942-baeb-6ddc4eb11d0d'), editable=False),
        ),
    ]
